import idem_azurerm.exec.azurerm.resource.group as group
import pytest


@pytest.mark.asyncio
async def test_get(mock_hub):
    """
    """
    #await group.get(mock_hub, "name")
    #mock_hub.exec.utils.azurerm.log_cloud_error.assert_called_once_with("resource")
